### ISSUE TITLE
Error: Division by zero

### ISSUE THREAD

**Issue by joerg-s** [asdfjkl/yahb#4]
Hallo,

I wanted to try yahb, but it did not really work.

Scenario: In Windows 10 a share from my Synology NAS is mounted as J:, it contains a directory named Backups. (Maybe it's important: Windows 10 runs in a virtual box).

I tried 
**yahb c:\Users\joerg\Documents j:\Backups /s**

Output:
_creating list of directories ...
ERR:c:\Users\joerg\Documents\Eigene Videos:Der Zugriff auf den Pfad "c:\Users\joerg\Documents\Eigene Videos" wurde verweigert.
ERR:c:\Users\joerg\Documents\Eigene Musik:Der Zugriff auf den Pfad "c:\Users\joerg\Documents\Eigene Musik" wurde verweigert.
ERR:c:\Users\joerg\Documents\Eigene Bilder:Der Zugriff auf den Pfad "c:\Users\joerg\Documents\Eigene Bilder" wurde verweigert.
creating list of directories ... DONE
creating list of files ...
creating list of files ... DONE
unable to identify a previous backup location, copying all
copying files:  [          ]   0%
Unbehandelte Ausnahme: System.DivideByZeroException: Es wurde versucht, durch 0 (null) zu teilen.
   bei yahb.CopyModule.doCopy()
   bei yahb.Program.Main(String[] args)_

Result: The backup directory ist created as expected:
j:\Backups\202004031108\c__\Users\joerg\Documents
But this contains only the directories of the source, which are all empty. No files were copied. 

Do I make a mistake here? Should I change or check something? Or is there some bug?

I hope my comment helps to improve your project,
regards and good health,
Jörg

**Comment by asdfjkl** [comment]
Thanks for your bug report. There are two issues here:
1.) No access to "C:\Users\joerg\Documents\Eigene Bilder" - that's normal, because this directory does not really exist, it's a junction point linking to "C:\User\joerg\Pictures" (some oddity of Windows due to localisation). I.e. if you want to backup your pictures, then pass "C:\User\joerg\Pictures" (or put all directories in a text-file FILENAME.TXT and use the /id:FILENAME.TXT option
2.) ...but yahb should not crash with a DivideByZeroException. Are you using version 1.0.3.0? If so, then that's a bug which I can currently not reproduce here...

**Comment by asdfjkl** [comment]
I'd highly appreciate if you could test wether the attached version of yahb fixes your problem.

[yahb_1.0.4.0_beta.zip](https://github.com/asdfjkl/yahb/files/4434507/yahb_1.0.4.0_beta.zip)

**Comment by joerg-s** [comment]
First, I do agree that the first point is not an issue: I don't need backups of some soft links that Microsoft decided to put into my folders...

And, much more important, the other bug is gone! I ran your program a few times, and it created just the right structure of files and hard links. Well done and pretty fast, asdfjkl (Dominik), I appreciate that.
Thank you, kind regards,
Jörg
